-- Dados fictícios para teste
MERGE INTO ficha_tecnica (id, estagio, tipo_solicitacao, tipo, codigo, descricao, cor, composicao, gramatura, fornecedor, referencia, ref_fornecedor, categoria_produto, marca, marca_que_comprou, marca_que_utiliza, largura, minimo_compra, preco_usd, preco_reais, status_pedido, colecao, status_colecao, minimo, quantidade_comprada, numero_pedido, data_colocacao_pedido, nome_navio, data_saida_origem, data_chegada_destino, status_amostra_cor, data_amostra_cor, data_aprovacao_amostra_cor, observacao_amostra_cor, status_amostra_producao, data_amostra_producao, data_aprovacao_amostra_producao, observacao_amostra_producao, foto_path)
KEY(id) VALUES
(1, 'Desenvolvimento', 'Nova', 'TECIDO', 'TEC-001', 'Malha Jersey Premium', 'Azul Marinho', '95% Algodão, 5% Elastano', '180g/m²', 'Textile Shanghai Co.', 'REF-SH-2026', 'FS-JER-001', 'Malha', 'BIMBI', 'ANIME', 'MOMI', '1,80m', 500, 3.50, 17.85, 'EMBARCADO', 'Inverno 2027', 'Inverno 2027', 300, 1200, 'PED-2026-001', DATE '2026-01-15', 'MSC Gülsün', DATE '2026-02-20', DATE '2026-04-05', 'APROVADO', DATE '2026-01-28', DATE '2026-02-18', 'Cor aprovada na segunda submissão', 'PENDENTE', NULL, NULL, NULL, NULL);

MERGE INTO ficha_tecnica (id, estagio, tipo_solicitacao, tipo, codigo, descricao, cor, composicao, gramatura, fornecedor, referencia, ref_fornecedor, categoria_produto, marca, marca_que_comprou, marca_que_utiliza, largura, minimo_compra, preco_usd, preco_reais, status_pedido, colecao, status_colecao, minimo, quantidade_comprada, numero_pedido, data_colocacao_pedido, nome_navio, data_saida_origem, data_chegada_destino, status_amostra_cor, data_amostra_cor, data_aprovacao_amostra_cor, observacao_amostra_cor, status_amostra_producao, data_amostra_producao, data_aprovacao_amostra_producao, observacao_amostra_producao, foto_path)
KEY(id) VALUES
(2, 'Produção', 'Reposição', 'TECIDO', 'TEC-002', 'Sarja Stretch', 'Preto', '98% Algodão, 2% Spandex', '260g/m²', 'Guangzhou Fabrics Ltd.', 'REF-GZ-450', 'GZ-SAR-002', 'Plano', 'YOUCCIE', 'MOMI', 'AUTHORIA', '1,50m', 1000, 4.20, 21.42, 'RECEBIDO', 'Verão 2027', 'Verão 2027', 500, 3000, 'PED-2026-002', DATE '2025-11-10', 'Ever Given', DATE '2025-12-15', DATE '2026-02-01', 'APROVADO', DATE '2025-11-25', DATE '2025-12-20', 'Aprovada de primeira', 'APROVADO', DATE '2025-12-05', DATE '2025-12-28', 'Qualidade conforme esperado', NULL);

MERGE INTO ficha_tecnica (id, estagio, tipo_solicitacao, tipo, codigo, descricao, cor, composicao, gramatura, fornecedor, referencia, ref_fornecedor, categoria_produto, marca, marca_que_comprou, marca_que_utiliza, largura, minimo_compra, preco_usd, preco_reais, status_pedido, colecao, status_colecao, minimo, quantidade_comprada, numero_pedido, data_colocacao_pedido, nome_navio, data_saida_origem, data_chegada_destino, status_amostra_cor, data_amostra_cor, data_aprovacao_amostra_cor, observacao_amostra_cor, status_amostra_producao, data_amostra_producao, data_aprovacao_amostra_producao, observacao_amostra_producao, foto_path)
KEY(id) VALUES
(3, 'Aprovação', 'Nova', 'ACESSORIO', 'ACE-001', 'Botão Metálico 18mm', 'Dourado', 'Liga de Zinco', NULL, 'YKK China', 'REF-YKK-18', 'YKK-BOT-018', 'Aviamento', 'ANIME', 'ANIME', 'ANIME', NULL, 5000, 0.12, 0.61, 'EM_ANDAMENTO', 'Inverno 2027', 'Inverno 2027', 2000, 10000, 'PED-2026-003', DATE '2026-02-20', NULL, NULL, NULL, 'APROVADO', DATE '2026-03-01', DATE '2026-03-28', 'Cor dourada conforme referência Pantone', 'REPROVADO', DATE '2026-03-05', NULL, 'Acabamento com rebarbas. Solicitada nova amostra.', NULL);

MERGE INTO ficha_tecnica (id, estagio, tipo_solicitacao, tipo, codigo, descricao, cor, composicao, gramatura, fornecedor, referencia, ref_fornecedor, categoria_produto, marca, marca_que_comprou, marca_que_utiliza, largura, minimo_compra, preco_usd, preco_reais, status_pedido, colecao, status_colecao, minimo, quantidade_comprada, numero_pedido, data_colocacao_pedido, nome_navio, data_saida_origem, data_chegada_destino, status_amostra_cor, data_amostra_cor, data_aprovacao_amostra_cor, observacao_amostra_cor, status_amostra_producao, data_amostra_producao, data_aprovacao_amostra_producao, observacao_amostra_producao, foto_path)
KEY(id) VALUES
(4, 'Desenvolvimento', 'Nova', 'TECIDO', 'TEC-003', 'Viscose Estampada Floral', 'Vermelho Estampado', '100% Viscose', '130g/m²', 'Hangzhou Silk Trading', 'REF-HZ-FL01', 'HZ-VIS-004', 'Plano', 'MOMI', 'AUTHORIA', 'MOMI', '1,45m', 800, 2.80, 14.28, 'EM_ANDAMENTO', 'Verão 2027', 'Verão 2027', 400, 2000, 'PED-2026-004', DATE '2026-03-01', NULL, NULL, NULL, 'PENDENTE', NULL, NULL, 'Aguardando envio da lab-dip', 'PENDENTE', NULL, NULL, NULL, NULL);

MERGE INTO ficha_tecnica (id, estagio, tipo_solicitacao, tipo, codigo, descricao, cor, composicao, gramatura, fornecedor, referencia, ref_fornecedor, categoria_produto, marca, marca_que_comprou, marca_que_utiliza, largura, minimo_compra, preco_usd, preco_reais, status_pedido, colecao, status_colecao, minimo, quantidade_comprada, numero_pedido, data_colocacao_pedido, nome_navio, data_saida_origem, data_chegada_destino, status_amostra_cor, data_amostra_cor, data_aprovacao_amostra_cor, observacao_amostra_cor, status_amostra_producao, data_amostra_producao, data_aprovacao_amostra_producao, observacao_amostra_producao, foto_path)
KEY(id) VALUES
(5, 'Cancelado', 'Reposição', 'ACESSORIO', 'ACE-002', 'Zíper Invisível 50cm', 'Branco', 'Nylon', NULL, 'SBS Zipper Co.', 'REF-SBS-50', 'SBS-ZIP-050', 'Aviamento', 'AUTHORIA', 'MOMI', 'ANIME', NULL, 3000, 0.35, 1.79, 'CANCELADO', 'Inverno 2027', 'Inverno 2027', 1000, 5000, 'PED-2026-005', DATE '2026-01-05', 'CMA CGM Marco Polo', DATE '2026-01-25', DATE '2026-03-10', 'REPROVADO', DATE '2026-01-15', NULL, 'Tom de branco diferente do solicitado. Pedido cancelado.', 'PENDENTE', NULL, NULL, 'Cancelado antes da amostra de produção', NULL);

MERGE INTO ficha_tecnica (id, estagio, tipo_solicitacao, tipo, codigo, descricao, cor, composicao, gramatura, fornecedor, referencia, ref_fornecedor, categoria_produto, marca, marca_que_comprou, marca_que_utiliza, largura, minimo_compra, preco_usd, preco_reais, status_pedido, colecao, status_colecao, minimo, quantidade_comprada, numero_pedido, data_colocacao_pedido, nome_navio, data_saida_origem, data_chegada_destino, status_amostra_cor, data_amostra_cor, data_aprovacao_amostra_cor, observacao_amostra_cor, status_amostra_producao, data_amostra_producao, data_aprovacao_amostra_producao, observacao_amostra_producao, foto_path)
KEY(id) VALUES
(6, 'Produção', 'Nova', 'TECIDO', 'TEC-004', 'Linho Puro', 'Bege Natural', '100% Linho', '200g/m²', 'Jiangsu Linen Export', 'REF-JS-LN01', 'JS-LIN-006', 'Plano', 'BIMBI', 'ANIME', 'AUTHORIA', '1,40m', 300, 6.50, 33.15, 'EMBARCADO', 'Verão 2027', 'Verão 2027', 200, 800, 'PED-2026-006', DATE '2026-02-10', 'COSCO Shipping Leo', DATE '2026-03-01', DATE '2026-04-15', 'APROVADO', DATE '2026-02-25', DATE '2026-03-22', 'Tonalidade perfeita', 'APROVADO', DATE '2026-02-28', DATE '2026-03-30', 'Toque e caimento aprovados', NULL);

MERGE INTO ficha_tecnica (id, estagio, tipo_solicitacao, tipo, codigo, descricao, cor, composicao, gramatura, fornecedor, referencia, ref_fornecedor, categoria_produto, marca, marca_que_comprou, marca_que_utiliza, largura, minimo_compra, preco_usd, preco_reais, status_pedido, colecao, status_colecao, minimo, quantidade_comprada, numero_pedido, data_colocacao_pedido, nome_navio, data_saida_origem, data_chegada_destino, status_amostra_cor, data_amostra_cor, data_aprovacao_amostra_cor, observacao_amostra_cor, status_amostra_producao, data_amostra_producao, data_aprovacao_amostra_producao, observacao_amostra_producao, foto_path)
KEY(id) VALUES
(7, 'Aprovação', 'Reposição', 'ACESSORIO', 'ACE-003', 'Etiqueta Tecida Marca', 'Preto e Branco', 'Poliéster', NULL, 'Wuxi Label Factory', 'REF-WX-ET01', 'WX-ETQ-007', 'Etiqueta', 'YOUCCIE', 'AUTHORIA', 'MOMI', NULL, 10000, 0.05, 0.26, 'RECEBIDO', 'Inverno 2027', 'Inverno 2027', 5000, 20000, 'PED-2026-007', DATE '2025-12-01', 'Maersk Sealand', DATE '2025-12-20', DATE '2026-02-10', 'APROVADO', DATE '2025-12-10', DATE '2026-01-05', 'Layout e cores aprovados', 'APROVADO', DATE '2025-12-18', DATE '2026-01-12', 'Qualidade da tecelagem OK', NULL);

MERGE INTO ficha_tecnica (id, estagio, tipo_solicitacao, tipo, codigo, descricao, cor, composicao, gramatura, fornecedor, referencia, ref_fornecedor, categoria_produto, marca, marca_que_comprou, marca_que_utiliza, largura, minimo_compra, preco_usd, preco_reais, status_pedido, colecao, status_colecao, minimo, quantidade_comprada, numero_pedido, data_colocacao_pedido, nome_navio, data_saida_origem, data_chegada_destino, status_amostra_cor, data_amostra_cor, data_aprovacao_amostra_cor, observacao_amostra_cor, status_amostra_producao, data_amostra_producao, data_aprovacao_amostra_producao, observacao_amostra_producao, foto_path)
KEY(id) VALUES
(8, 'Desenvolvimento', 'Nova', 'TECIDO', 'TEC-005', 'Moletom Flanelado', 'Cinza Mescla', '80% Algodão, 20% Poliéster', '320g/m²', 'Textile Shanghai Co.', 'REF-SH-MOL01', 'FS-MOL-008', 'Malha', 'BIMBI', 'MOMI', 'ANIME', '1,70m', 600, 5.10, 26.01, 'EM_ANDAMENTO', 'Inverno 2027', 'Inverno 2027', 400, 1500, 'PED-2026-008', DATE '2026-03-05', NULL, NULL, NULL, 'PENDENTE', NULL, NULL, 'Lab-dip enviada, aguardando retorno', 'PENDENTE', NULL, NULL, NULL, NULL);
